MIME-Version: 1.0
Received: by 2002:a4f:a0c9:0:0:0:0:0 with HTTP; Tue, 5 Jun 2018 08:56:44 -0700 (PDT)
From: testTeam Bravo <kijiji.adserver1234@gmail.com>
Date: Tue, 5 Jun 2018 09:56:44 -0600
Message-ID: <CAKdTeANd4HhxwLt+ZdS6vNN5=vuswd6KjpZJJXvAC2YEDeoVbA@mail.gmail.com>
Subject: new request
To: kijiji.adserver1234@gmail.com
Content-Type: multipart/alternative; boundary="000000000000d26fa0056de718bd"

--000000000000d26fa0056de718bd
Content-Type: text/plain; charset="UTF-8"

URL : "https://www.kijiji.ca/b-cars-trucks/calgary/convertible__
coupe__hatchback__other+body+type__sedan__wagon-mazda-mx5mia
ta/c174l1700199a138a54a1000054"

Delay: 10 seconds

Exclude: wanted, parts

--000000000000d26fa0056de718bd
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><span style=3D"color:rgb(34,34,34);font-family:arial,sans-=
serif;font-size:12.8px;font-style:normal;font-variant-ligatures:normal;font=
-variant-caps:normal;font-weight:400;letter-spacing:normal;text-align:start=
;text-indent:0px;text-transform:none;white-space:normal;word-spacing:0px;te=
xt-decoration-style:initial;text-decoration-color:initial;background-color:=
rgb(255,255,255);float:none;display:inline">URL :<span>=C2=A0&quot;</span><=
/span><a href=3D"https://www.kijiji.ca/b-cars-trucks/calgary/convertible__c=
oupe__hatchback__other+body+type__sedan__wagon-mazda-mx5miata/c174l1700199a=
138a54a1000054" target=3D"_blank" style=3D"color:rgb(17,85,204);font-family=
:arial,sans-serif;font-size:12.8px;font-style:normal;font-variant-ligatures=
:normal;font-variant-caps:normal;font-weight:400;letter-spacing:normal;text=
-align:start;text-indent:0px;text-transform:none;white-space:normal;word-sp=
acing:0px;background-color:rgb(255,255,255)">https://www.kijiji.ca/b-car<wb=
r>s-trucks/calgary/convertible__<wbr>coupe__hatchback__other+body+t<wbr>ype=
__sedan__wagon-mazda-mx5mia<wbr>ta/c174l1700199a138a54a1000054</a><span sty=
le=3D"color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;fon=
t-style:normal;font-variant-ligatures:normal;font-variant-caps:normal;font-=
weight:400;letter-spacing:normal;text-align:start;text-indent:0px;text-tran=
sform:none;white-space:normal;word-spacing:0px;text-decoration-style:initia=
l;text-decoration-color:initial;background-color:rgb(255,255,255);float:non=
e;display:inline"><wbr>&quot;</span><div style=3D"color:rgb(34,34,34);font-=
family:arial,sans-serif;font-size:12.8px;font-style:normal;font-variant-lig=
atures:normal;font-variant-caps:normal;font-weight:400;letter-spacing:norma=
l;text-align:start;text-indent:0px;text-transform:none;white-space:normal;w=
ord-spacing:0px;text-decoration-style:initial;text-decoration-color:initial=
;background-color:rgb(255,255,255)"><br></div><div style=3D"color:rgb(34,34=
,34);font-family:arial,sans-serif;font-size:12.8px;font-style:normal;font-v=
ariant-ligatures:normal;font-variant-caps:normal;font-weight:400;letter-spa=
cing:normal;text-align:start;text-indent:0px;text-transform:none;white-spac=
e:normal;word-spacing:0px;text-decoration-style:initial;text-decoration-col=
or:initial;background-color:rgb(255,255,255)">Delay: 10 seconds</div><div st=
yle=3D"color:rgb(34,34,34);font-family:arial,sans-serif;font-size:12.8px;fo=
nt-style:normal;font-variant-ligatures:normal;font-variant-caps:normal;font=
-weight:400;letter-spacing:normal;text-align:start;text-indent:0px;text-tra=
nsform:none;white-space:normal;word-spacing:0px;text-decoration-style:initi=
al;text-decoration-color:initial;background-color:rgb(255,255,255)"><br></d=
iv><div style=3D"color:rgb(34,34,34);font-family:arial,sans-serif;font-size=
:12.8px;font-style:normal;font-variant-ligatures:normal;font-variant-caps:n=
ormal;font-weight:400;letter-spacing:normal;text-align:start;text-indent:0p=
x;text-transform:none;white-space:normal;word-spacing:0px;text-decoration-s=
tyle:initial;text-decoration-color:initial;background-color:rgb(255,255,255=
)">Exclude: wanted, parts</div><br></div>

--000000000000d26fa0056de718bd--


A
A
                                
